docs/contracts/payment-protocol.md

Update ImmersvePaymentProtocol to latest version and address on Mumbai
Only public functions are documented now
[Ticket Link](https://www.notion.so/immersve/Smart-Contract-upgrade-Migration-00bf2e156ddc4aa5a4dc84c83e1e053d?pvs=4)

Update ImmersvePaymentProtocol to latest version

---

docs/guides/non-custodial wallets/authentication.md

Steps: Using either using the request functionality on the API Endpoint page, or the provided curls.
1. Generate Challenge
2. Connect Metamask to CodePen.
3. Copy the challenge message into CodePen.
4. CodePen outputs both signature and the stringified object containing the signed challenge and signature.
5. Login to get the token.
Slack: https://immersve.slack.com/archives/C03471T0RMF/p1688419775959049
Ticket Link: _link_here_
[Signing Challenge CodePen](https://codepen.io/Immersve/pen/zYMpExJ) - will make a little bit prettier shortly.
Expanded script:

Update the quick start signing challenge to be easier and safer to use

---

docs/guides/non-custodial wallets/authentication.md
openapi/endpoints/login/models/challenge-request.yaml
openapi/endpoints/login/siwe-generate-challenge.yaml

- Add new fields to generate challenge endpoint
Ticket Link: N/A

Add clientApplicationId and scopes to generate challenge

---

docs/contracts/payment-protocol.md

The smart contract has deployed on the mainnet. so update the proxy address of prod 
Ticket Link: [_link_here_](https://www.notion.so/immersve/Card-funding-v1-smart-contract-Polygon-mainnet-deployment-86d94ff4c92b41feb2212f080c849308?pvs=4)

update proxy prod address

---

openapi/endpoints/cards/card-order.yaml
openapi/endpoints/cards/models/card-order-request.yaml

- Add `cardProgramId` as a required body field to order card endpoint
Ticket Link: https://www.notion.so/immersve/Update-Card-Creation-to-use-Funding-source-4f14c04a97df4f43855926fe92070dc4?pvs=4

Add cardProgramId to create card endpoint

---

openapi/endpoints/login/models/challenge-request.yaml

This would be a more accurate description
Ticket Link: none

Use the correct word in url field description

---

openapi/endpoints/funding-sources/funding-sources-list.yaml
openapi/endpoints/funding-sources/models/funding-source.yaml
openapi/endpoints/funding-sources/models/list-funding-sources-result.yaml
openapi/immersve.yaml

Docs for list funding sources endpoint
Ticket Link: https://www.notion.so/immersve/Endpoint-documentation-bdd490f0a6504ce6bb3830a4c06bf634?pvs=4

Add list funding sources endpoint

---

openapi/endpoints/funding-source/create-funding-source.yaml
openapi/endpoints/funding-source/models/create-funding-source-eoa.yaml
openapi/endpoints/funding-source/models/create-funding-source-erc-1271.yaml
openapi/immersve.yaml

Add api doc
Ticket Link: https://www.notion.so/immersve/Create-Funding-source-API-d5aebbe2274a4d498d645a526e9459b0?pvs=4

Add claim funding source api

---

openapi/endpoints/cards/card-order.yaml
openapi/endpoints/cards/create-card-async.yaml
openapi/endpoints/cards/models/create-card-async-request.yaml
openapi/endpoints/cards/models/create-card-async-response.yaml
openapi/endpoints/prerequisites/models/get-spending-prerequisite-request.yaml
openapi/endpoints/prerequisites/models/get-spending-prerequisite-response.yaml
openapi/endpoints/prerequisites/spending-prerequisites.yaml
openapi/immersve.yaml

Add spending-prerequisite
Add create-card-async
Ticket Link: 
[spending-prerequisites](https://www.notion.so/immersve/Endpoint-documentation-f839590499db4836a3c7ad945abe5c1e?pvs=4) 
[create-card-async](https://www.notion.so/immersve/Endpoint-documentation-76ff28cc71d94922b7bdb9ff02eb1f75?pvs=4)

add spending-prerequisite and create-card-async

---

openapi/endpoints/currency/currency-convert.yaml
openapi/endpoints/currency/models/currency-conversion.yaml

Enforce minor units on currency conversion route.
PR to effect change in amethyst: https://github.com/immersve/amethyst/pull/932
Ticket Link: https://www.notion.so/immersve/Default-Simulator-Endpoints-to-Minor-Units-c0b450d032604419872fc7656a1780b7

Chore(currencyConversion) - Remove minor units flag

---

openapi/endpoints/cards/card-get.yaml
openapi/endpoints/cards/cards-list.yaml
openapi/endpoints/cards/models/get-card.yaml
openapi/endpoints/transactions/models/transaction.yaml
openapi/endpoints/transactions/transaction-get.yaml
openapi/endpoints/transactions/transactions-list.yaml
openapi/immersve.yaml

Remove the flags and update the api responses for these endpoints:
getCard
getCards
getTransaction
getTransactions
PRs to effect change in amethyst: 
https://github.com/immersve/amethyst/pull/933
https://github.com/immersve/amethyst/pull/936
Ticket Link: https://www.notion.so/immersve/Default-Simulator-Endpoints-to-Minor-Units-c0b450d032604419872fc7656a1780b7

Chore(transactions & cards) - Remove minor units flag

---

openapi/endpoints/transactions/models/transaction.yaml

Add `creditDebitIndicator` to transaction model
[Ticket](https://www.notion.so/immersve/Docs-Add-debitCreditIndicator-9ae4f4ab94234ad3ba5ae35f854bdb8b?pvs=4)

add creditDebitIndicator to transaction

---

docs/guides/monetary-units.md

Add a monetary units guide.
A data types page is not needed at this point.
Ticket Link: [_link_here_](https://www.notion.so/immersve/Create-data-types-docs-page-f1012e0f4028407bbb8a849c87c90aa8?pvs=4)

Monetary Units Guide

---

openapi/endpoints/kyc/get-kyc-profile.yaml
openapi/endpoints/kyc/models/get-kyc-profile-response.yaml
openapi/immersve.yaml

Get KYC Profile endpoint
Ticket Link: https://www.notion.so/immersve/Document-56362aada50f4134910b99f4b7512f22?pvs=4
**Test Plan:**

Get KYC profile endpoint

---

openapi/endpoints/accounts/accounts-create.yaml
openapi/endpoints/asset-activities/asset-activities-get.yaml
openapi/endpoints/asset-activities/asset-activities-list.yaml
openapi/endpoints/cards/card-cancel.yaml
openapi/endpoints/cards/card-get.yaml
openapi/endpoints/cards/card-pan-token.yaml
openapi/endpoints/cards/cards-list.yaml
openapi/endpoints/cards/create-card-async.yaml
openapi/endpoints/currency/currency-convert.yaml
openapi/endpoints/funding-sources/list-funding-sources.yaml
openapi/endpoints/login/siwe-generate-challenge.yaml
openapi/endpoints/login/siwe-login.yaml
openapi/endpoints/prerequisites/spending-prerequisites.yaml
openapi/endpoints/simulator/authorize.yaml
openapi/endpoints/simulator/clear.yaml
openapi/endpoints/simulator/reverse.yaml
openapi/endpoints/transactions/transaction-get.yaml
openapi/endpoints/transactions/transactions-list.yaml

Make 400 description uniform.
Add 400 and 403 to endpoints where missing.
Ticket Link: https://www.notion.so/immersve/Improve-logging-patterns-baced7fa833d4bf89b9091bc2e92e037

Chore - error formatting - Make 400 use uniform and add errors to endpoints where missing

---

openapi/endpoints/accounts/accounts-create.yaml
openapi/endpoints/accounts/accounts-list.yaml
openapi/endpoints/asset-activities/asset-activities-get.yaml
openapi/endpoints/asset-activities/asset-activities-list.yaml
openapi/endpoints/cards/cards-list.yaml
openapi/endpoints/cards/create-card-async.yaml
openapi/endpoints/funding-sources/list-funding-sources.yaml
openapi/endpoints/funding-sources/register-funding-source.yaml
openapi/endpoints/kyc/retrieve-partner-kyc-statement.yaml
openapi/endpoints/prerequisites/spending-prerequisites.yaml

Remove NOT_FOUND errorCode examples
Make 403 descriptions uniform. 
Kept detailed examples where given.
Related amethyst PR: https://github.com/immersve/amethyst/pull/965
calcite PR: https://github.com/immersve/calcite/pull/226
Ticket Link: https://www.notion.so/immersve/Improve-logging-patterns-baced7fa833d4bf89b9091bc2e92e037

Chore - Error codes - 403

---

openapi/endpoints/kyc/submit-partner-kyc-statement.yaml

Ticket Link:related PR https://github.com/immersve/amethyst/pull/1142

refactor(KYC): Add KYC_STATEMENTS_NOT_ALLOWED error code

---

openapi/endpoints/accounts/models/create-account-request.yaml
openapi/endpoints/accounts/models/create-custodial-cardholder-account-request.yaml

Update docs for custodial cardholder creation
Related PR in calcite: https://github.com/immersve/calcite/pull/248
Ticket Link: https://immersve.slack.com/archives/C05416XG5UZ/p1699954840234079

Update docs for custodial cardholder creation

---

openapi/endpoints/kyc/get-kyc-profile.yaml
openapi/models/kyc-params.yaml

- use correct auth scheme for GET KYC profile endpoint
- explain statuses returned by KYC spending prerequisites
Ticket Link: https://immersve.slack.com/archives/C04EDU7MYCB/p1700562747397129?thread_ts=1700485762.996869&cid=C04EDU7MYCB

Improve KYC documentation

---

openapi/endpoints/kyc/get-kyc-profile.yaml
openapi/endpoints/kyc/retrieve-partner-kyc-statement.yaml

Related PR: 
- https://github.com/immersve/amethyst/pull/1199
Ticket Link: https://immersve.slack.com/archives/C04EDU7MYCB/p1700683317961729?thread_ts=1700485762.996869&cid=C04EDU7MYCB

docs: Better error codes for KYC endpoints

---

openapi/endpoints/cards/create-card-async.yaml
openapi/endpoints/prerequisites/models/get-spending-prerequisite-response.yaml
openapi/endpoints/prerequisites/spending-prerequisites.yaml
openapi/models/contact-channel-email-params.yaml
openapi/models/contact-channel-phone-params.yaml

Add contact details related changes to
1. "Create a card"
2. "Get spending prerequisites"
Ticket Link: https://www.notion.so/Update-Immersve-docs-for-Create-Card-and-Prerequisites-3e13b3a335ee4a5084d0e7ffbcb4f6fb

Add contact details related changes to "Create a card" and "Get spending prerequisites"

---

openapi/endpoints/funding-channel/funding-channel-create.yaml
openapi/endpoints/funding-channel/funding-channel-get.yaml
openapi/endpoints/funding-channel/models/create-funding-channel.yaml
openapi/endpoints/funding-channel/models/get-funding-channel.yaml
openapi/immersve.yaml

https://www.notion.so/immersve/document-claim-fundingChannel-api-94c1a90ebe924363b45ec6d9dd3ad6cc?pvs=4

create a funding channel doc

---

openapi/immersve.yaml

api/funding-channels not /api/funding-channel

fix create funding channel

---

openapi/endpoints/funding-sources/models/create-funding-source-eoa.yaml
openapi/endpoints/funding-sources/models/create-funding-source-erc-1271.yaml
openapi/endpoints/funding-sources/models/funding-source.yaml

https://www.notion.so/immersve/update-createFundingSource-doc-03144eac3b914b648aaac34d7b61ff38?pvs=4

update createFundingSource to use fundingChannelId

---

docs/guides/card-funding.md
docs/guides/issue-a-virtual-card.md
docs/redirects/api-reference/register-funding-source.mdx
openapi/endpoints/funding-sources/create-funding-source.yaml
openapi/immersve.yaml

https://www.notion.so/immersve/update-createFundingSource-doc-03144eac3b914b648aaac34d7b61ff38?pvs=4

rename createFundingSource endpoint

---

openapi/endpoints/funding-sources/funding-source-interactions-get.yaml
openapi/endpoints/funding-sources/models/funding-source-interaction.yaml
openapi/endpoints/funding-sources/models/get-funding-source-interactions.yaml
openapi/immersve.yaml

document get Funding Source Interactions by Funding Source id api
Ticket Link: https://www.notion.so/immersve/documentation-7f7649c2b5f74f0288d8b2bdfe4fb72a?pvs=4

Feat(get-funding-source-interactions): Add documentation for get funding source interactions

---

openapi/models/page-info.yaml

remove previous cursor from pageInfo object

remove previous cursor

---

openapi/endpoints/funding-sources/funding-source-interactions-get.yaml
openapi/endpoints/funding-sources/models/funding-source-interaction.yaml
openapi/endpoints/funding-sources/models/get-funding-source-interactions.yaml
openapi/endpoints/funding-sources/models/list-funding-source-interactions.yaml

update list funding source interactions with `description` and `creditOrDebitIndicator` object

update list funding source interactions

---

openapi/endpoints/funding-channel/models/funding-channel.yaml

storageAddress for fundingChannel

---

openapi/endpoints/funding-channel/funding-channels-list.yaml
openapi/endpoints/funding-channel/models/get-funding-channels.yaml
openapi/endpoints/funding-channel/models/list-funding-channels.yaml
openapi/immersve.yaml

Add query parameters and page info for list funding channels pagination
Ticket Link: https://www.notion.so/immersve/update-docs-for-list-funding-channels-pagination-6d8d2072be9641289b5d59ff1c95fda6?pvs=4

(feat) Update list funding channels

---

imsv-docs-docusaurus/openapi/endpoints/cards/cards-list.yaml
imsv-docs-docusaurus/openapi/endpoints/funding-channel/funding-channels-list.yaml
imsv-docs-docusaurus/openapi/endpoints/funding-sources/funding-source-interactions-get.yaml
imsv-docs-docusaurus/openapi/endpoints/transactions/transactions-list.yaml

It wasn't obvious how we do pagination.
Ticket Link: [slack](https://immersve.slack.com/archives/C058ZATEC6A/p1708022635176109)

Adding explanation of pagination.

---

imsv-docs-docusaurus/openapi/endpoints/prerequisites/models/get-spending-prerequisite-request.yaml
imsv-docs-docusaurus/openapi/endpoints/prerequisites/spending-prerequisites.yaml
imsv-docs-docusaurus/openapi/models/kyc-params.yaml

Add KYC type and redirect URL in spending prerequisites request and kycURL in the response
Ticket Link: https://www.notion.so/immersve/Update-Immersve-docs-aab41c5982194073b808651677385d17

Feature: Add KYC type and redirect URL in spending prerequisites request and kycURL in the response

---

imsv-docs-docusaurus/openapi/endpoints/login/auth-token-exchange.yaml
imsv-docs-docusaurus/openapi/endpoints/login/models/auth-token-exchange.yaml
imsv-docs-docusaurus/openapi/endpoints/login/models/login-response.yaml
imsv-docs-docusaurus/openapi/immersve.yaml

**NOTE: do not merge until API is complete**
document refresh token endpoint
Ticket Link: https://www.notion.so/immersve/Refresh-token-endpoint-docs-59d3ab39e1ac4a16a2ae243323d3062d?pvs=4
Test deploy url: https://214-merge--jovial-scone-ec740d.netlify.app/api-reference/auth-token-exchange/

(Feat)Auth Token Exchange Documentation

---

imsv-docs-docusaurus/openapi/endpoints/funding-sources/get-funding-source.yaml
imsv-docs-docusaurus/openapi/immersve.yaml

Endpoint was added. Docs needed to match.

Add get funding source endpoint.

---

imsv-docs-astro/astro.config.mjs
imsv-docs-astro/src/content/docs/guides/cardholder-support.mdoc
imsv-docs-docusaurus/openapi/endpoints/imsv-support/models/create-support-session-result.yaml
imsv-docs-docusaurus/openapi/endpoints/imsv-support/models/create-support-session.yaml
imsv-docs-docusaurus/openapi/endpoints/imsv-support/support-session-create.yaml
imsv-docs-docusaurus/openapi/immersve.yaml

add cardholder support page
Ticket Link: [_link_here_](https://www.notion.so/immersve/API-documentation-abd064ffb3ff42e19df91b9bd7535a48?pvs=4)
Doc design page: https://www.notion.so/immersve/Cardholder-Support-7111016ecf4d450d9a29733d67bb28c2?pvs=4
Screenshots on localhost

feature(support): add cardholder support page

---

imsv-docs-astro/src/components/TokenTable.astro
imsv-docs-astro/src/content/docs/guides/supported-chains/ethereum.mdoc
imsv-docs-astro/src/content/docs/guides/supported-chains/polygon.mdoc

Fixes for https://github.com/immersve/immersve-docs/pull/235

Fix - Small fixes for previous PR

---

imsv-docs-astro/src/content/docs/guides/card-issuing-apps/creating-a-funding-channel.mdoc
imsv-docs-astro/src/content/docs/guides/funding-protocols/funding-protocols.mdoc
imsv-docs-astro/src/content/docs/guides/funding-protocols/universal-evm-smart-contract.mdoc
imsv-docs-astro/src/content/docs/index.mdoc
imsv-docs-astro/src/content/networks/ethereum-sepolia.md
imsv-docs-astro/src/content/networks/polygon-amoy.md
imsv-docs-astro/src/content/networks/polygon.md
imsv-docs-astro/src/redirects.yml

Universal EVM Smart Contract page renamed to Universal EVM Funding Protocol.
This is consistent with the design in the New Docs Pages.
Ticket Link: https://www.notion.so/immersve/379e51bc856c455390b30b69b73a32ad?v=bb50554a748a458b9ceefa6c50770f35

Update - Rename Universal EVM page

---

imsv-docs-astro/src/components/registry-views/protocols/DeployedFundingProtocolsTable.astro
imsv-docs-astro/src/content/docs/guides/supported-chains/polygon.mdoc
imsv-docs-astro/src/models/__tests__/models.test.mjs

Both polygon and ethereum pages are showing the wrong values for deployed addresses. See:
* https://docs.immersve.com/guides/polygon/
* https://docs.immersve.com/guides/ethereum/

Fix deployed protocol addresses

---

imsv-docs-docusaurus/openapi/immersve.yaml
package.json

Reorder sidebar navigation to make more sense
Remove old package.json script that no longer works.

Reorder authentication sidebar navigation section

---

imsv-docs-astro/package.json
yarn.lock

Even more dependabot updates

---

imsv-docs-astro/package.json
imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/create-funding-source-challenge.yaml
imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/create-funding-source-eoa.yaml
imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/create-funding-source-erc-1271.yaml
yarn.lock

Fix fundingAddress formatting on create funding source page (despite being defined as a string, docusaurus renders it as a number without the quotes 🤦🏻‍♂️
Ticket Link: [_link_here_](https://immersve.slack.com/archives/C06G54VDLM8/p1715584165678339?thread_ts=1715322719.244659&cid=C06G54VDLM8)

Fix funding address formatting

---

imsv-docs-astro/package.json
yarn.lock

Bump astro from 4.8.2 to 4.8.3

---

imsv-docs-astro/astro.config.mjs
imsv-docs-astro/src/content/docs/guides/countries.mdoc
imsv-docs-astro/src/content/docs/guides/regions.mdoc

Add region docs
Todo:
Ticket Link: https://www.notion.so/immersve/Create-a-guide-on-Immersve-conducted-KYC-document-KYC-regions-4042e70e9dd44a30b91031d37ae70154

feat(docs): Add region docs

---

imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
imsv-docs-docusaurus/openapi/endpoints/kyc/models/retrieve-kyc-statement-response.yaml
imsv-docs-docusaurus/openapi/endpoints/kyc/models/submit-kyc-statement-request.yaml

Update partner conducted KYC docs
Ticket Link: https://www.notion.so/immersve/Update-the-public-documentation-on-partner-conducted-KYC-c6a42d0cc7a14357a7dc681b0164e41f

feat(kyc): Add region to KYC statement endpoints 

---

imsv-docs-astro/src/content/docs/guides/regions.mdoc

Add Australia to supported regions in public docs
Ticket Link: https://www.notion.so/immersve/Add-Australia-to-supported-regions-in-public-docs-022c74b0baf749bd8b47beb0b81dc868

feat(region): Add Australia to supported regions in public docs

---

imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc
imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc

- remove unused `timestamp` field 
- add missing space
Ticket Link: none

cleanup KYC docs: remove unused timestamp field and add missing space

---

imsv-docs-astro/src/content/networks/polygon-amoy.md
imsv-docs-astro/src/models/__tests__/models.test.mjs

because Polygonscan has better tooling
Link to conversation where Damjan confirmed our Amoy contract is verified on Polygonscan now:
https://immersve.slack.com/archives/C06T24WH857/p1716525153477039

link to Amoy Polygonscan instead of oklink

---

.editorconfig
imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc
imsv-docs-astro/src/content/docs/guides/kyc/introduction.mdoc
imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc

Add 1 region 1 wallet warnings. Clarifying test docs for Immersve Conducted KYC.
Ticket Link: https://www.notion.so/immersve/Partner-Integration-docs-updates-4c4ad81f67ca434984ba1277ddff1f8b?pvs=4

Add 1 wallet 1 region warnings. Clarifying test docs for ICKYC

---

imsv-docs-astro/src/content/docs/resources/public-sandbox-account.mdoc

Resource page with public sandbox partner credentials

---

imsv-docs-docusaurus/openapi/endpoints/login/login-init.yaml
imsv-docs-docusaurus/openapi/endpoints/login/models/algorand-login-request.yaml
imsv-docs-docusaurus/openapi/endpoints/login/models/xrpl-login-request.yaml
imsv-docs-docusaurus/openapi/endpoints/login/signup.yaml

split the request payload, since its different for xrpl and algorand

split login request body for login/signup init

---

imsv-docs-astro/markdoc.config.mjs
imsv-docs-astro/src/components/Tab.astro
imsv-docs-astro/src/content/docs/guides/authentication.mdoc

- update auth guide
- add xrpl code and challenge message example
- update siwe code example
- add syncKey to tab
Ticket Link: https://www.notion.so/immersve/Update-auth-guide-fdfbfe310b214c0f9e47a75ef3f8816d?pvs=4
Test deploy url: https://318-merge--jovial-scone-ec740d.netlify.app/guides/authentication/

feat(auth): Update auth guide

---

imsv-docs-astro/src/components/registry-views/chains/SupportedChainsTable.astro
imsv-docs-astro/src/components/registry-views/protocols/DeployedFundingProtocolsTable.astro
imsv-docs-astro/src/content/config.ts
imsv-docs-astro/src/content/docs/guides/supported-chains/ethereum.mdoc
imsv-docs-astro/src/content/docs/guides/supported-chains/polygon.mdoc
imsv-docs-astro/src/content/networks/ethereum-sepolia.md
imsv-docs-astro/src/content/networks/polygon-amoy.md
imsv-docs-astro/src/content/networks/polygon.md
imsv-docs-astro/src/models/ContentRegistry.mjs
imsv-docs-astro/src/models/SupportedNetwork.mjs

add the names for supported networks on the supported chains table
add the name for supported network for the specific chain table

add networkNames to supportedChains table and chains table

---

imsv-docs-docusaurus/openapi/endpoints/login/models/siwe-login-request.yaml

fix(auth): Siwe Supported Network

---

imsv-docs-astro/src/content/docs/resources/postman-collection.mdoc

Instead of [title](url) mdoc links.
Per slack conversation:
https://immersve.slack.com/archives/C06G54VDLM8/p1718076569732259?thread_ts=1717998123.934879&cid=C06G54VDLM8

Use {% link /%} tags where possible

---

imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc

Remove expiry as an required field, add missing commas.

correct evidence for drivers license

---

imsv-docs-astro/src/components/registry-views/chains/SupportedChainsTable.astro
imsv-docs-astro/src/components/registry-views/protocols/FundingTypeTable.astro
imsv-docs-astro/src/content/config.ts
imsv-docs-astro/src/content/docs/guides/funding-protocols/funding-protocols.mdoc
imsv-docs-astro/src/content/docs/guides/funding-protocols/simulator-funding-protocol.mdoc
imsv-docs-astro/src/content/funding-types/simulator-usdc.md
imsv-docs-astro/src/models/ContentRegistry.mjs
imsv-docs-astro/src/models/FundingType.mjs
imsv-docs-astro/src/models/SupportedChain.mjs
imsv-docs-astro/src/models/SupportedNetwork.mjs
imsv-docs-astro/src/models/__tests__/models.test.mjs

Add guide for simulator funding protocol
[Preview](https://337-merge--jovial-scone-ec740d.netlify.app)

Simulator funding docs

---

imsv-docs-astro/src/content/networks/algorand-mainnet.md
imsv-docs-astro/src/content/networks/algorand-testnet.md

Ticket Link: https://www.notion.so/immersve/Audit-ALGO-contracts-58c622878acd4acfbd3eda649ba96c5b?pvs=4

Update Algorand appIds to audited versions

---

imsv-docs-docusaurus/openapi/endpoints/kyc/models/submit-kyc-statement-request.yaml

Ticket Link: https://www.notion.so/immersve/Mandatory-KYC-region-9be6c8a573b74fff9722826125e87b95?pvs=4

Declare all partner kyc statement attributes as required

---

imsv-docs-astro/src/content/docs/guides/authentication.mdoc
starlight/user-components/Tabs.astro

- Fix tabs styling. Could be better, but short-term fix until we get rid of tabs.
- Make script titles more explicit so it's very clear what network they are for.
Ticket Link: [Notion ticket](https://www.notion.so/immersve/Style-Improvement-tab-styles-1664433930ce43de8838b0eb9dabfac5?pvs=4)
Steps to test:
1. Go to Authentication guide
2. Click tabs half way down the page
3. They should work and be properly styled

Fix tabs styling

---

imsv-docs-astro/src/components/FooterNavigation.astro

make footer look like figma design, and improve responsiveness
Ticket Link: [Notion task](https://www.notion.so/immersve/Style-Improvement-footer-links-2e5441a8c8534442a2c5f0690199166a?pvs=4)

Style Improvement: footer links

---

imsv-docs-astro/public/postman/collection.json

Remove postman collection URL which contained some internal information we don't want to expose
Ticket Link: https://immersve.slack.com/archives/C06G54VDLM8/p1720476321362159

Remove Postman collection URL

---

imsv-docs-docusaurus/openapi/endpoints/kyc/models/UnstructuredAddress.yaml

Switch in for is.
Ticket Link: https://www.notion.so/immersve/Update-references-and-guides-be1cff22e93945dcb0c6bbb31b645039?pvs=4

fixup small typo

---

imsv-docs-astro/src/components/FooterNavigation.astro

make sure footer links never wrap at any screenshot
Ticket Link: https://immersve.slack.com/archives/C06G54VDLM8/p1720518266406409

make sure footer links never wrap at any screenshot

---

imsv-docs-astro/src/content/docs/guides/card-issuing-apps/issue-a-virtual-card.mdoc

Ticket Link: https://immersve.slack.com/archives/C06G54VDLM8/p1719954877522739

Reword issue virtual card guide opener

---

imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc
imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
imsv-docs-docusaurus/openapi/endpoints/prerequisites/models/get-spending-prerequisite-response.yaml
imsv-docs-docusaurus/openapi/endpoints/prerequisites/spending-prerequisites.yaml

According to the changes made in [Spending prerequisites returns all prerequisites](https://www.notion.so/immersve/Spending-prerequisites-returns-all-prerequisites-ac364511150b4511a8b34e2629923695)  story
Ticket Link: https://www.notion.so/immersve/Update-docs-and-guides-ffea4c52834746bebe084bd8b455d660

Update spending prerequisites docs

---

imsv-docs-astro/src/content/docs/guides/funding-protocols/flexi-algorand-funding-protocol.mdoc
imsv-docs-astro/src/content/networks/algorand-mainnet.md
imsv-docs-astro/src/content/networks/algorand-testnet.md

Ticket Link: https://immersve.slack.com/archives/C05MLBYKZAL/p1721180175558409
[Preview](https://375-merge--jovial-scone-ec740d.netlify.app/)

Updating algorand appIds after state changes requiring re-deployment

---

imsv-docs-astro/public/postman/collection.json
imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc

1. Updates the ordering of the guideline
2. Removes erroneous parameters from Partner Conducted Kyc request in Postman Collection, updates the ordering of the values to match the ordering in the docs.
Ticket Link: https://immersve.slack.com/archives/C04UUJR3G2X/p1721288116868469

Fixup Partner Conducted KYC example

---

imsv-docs-astro/ec.config.mjs
imsv-docs-astro/markdoc.config.mjs
imsv-docs-astro/package.json
imsv-docs-astro/src/components/CodeFence.astro
imsv-docs-astro/src/content/docs/guides/authentication.mdoc
imsv-docs-astro/src/content/docs/guides/card-issuing-apps/creating-a-funding-channel.mdoc
imsv-docs-astro/src/content/docs/guides/card-issuing-apps/custodial-on-chain-card-issuing-integration.mdoc
imsv-docs-astro/src/content/docs/guides/card-issuing-apps/fetching-secure-card-information.mdoc
imsv-docs-astro/src/content/docs/guides/core-concepts/card-funding.mdoc
imsv-docs-astro/src/content/docs/guides/http-status-codes.mdoc
imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc
imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
imsv-docs-astro/src/content/docs/guides/reports/authorization-reports.mdoc
imsv-docs-astro/src/content/docs/guides/reports/clearing-reports.mdoc
starlight/components/imsv/Prose.astro
yarn.lock

Ticket Link: https://www.notion.so/immersve/New-Code-Block-Style-fb63f4b3ec9b45bf850adeca24ed9996?pvs=4

Use Expressive Code component for all code blocks

---

imsv-docs-astro/src/content/docs/guides/card-issuing-apps/custodial-on-chain-card-issuing-integration.mdoc
imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc
imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc

kycRegion is now two letters format
Ticket Link: [_link_here_
](https://immersve.slack.com/archives/C06G54VDLM8/p1721761372172809?thread_ts=1721735897.594719&cid=C06G54VDLM8)

kycRegion is now two letters format

---

starlight/components/imsv/Header.astro

fix header alignment on mobile
Ticket Link: https://immersve.slack.com/archives/C06G54VDLM8/p1722201212177949

fix header alignment on mobile

---

imsv-docs-docusaurus/openapi/endpoints/login/signup.yaml

Better description of the required next step.
https://394-merge--jovial-scone-ec740d.netlify.app

Signup description expanded in style of login init.

---

imsv-docs-astro/src/content/docs/guides/authentication.mdoc

The immersve baseurl was missing. Code has also been cleaned up so that:
* parameters are clearly separated
* code duplication for login/signup is removed
* can supply algo account from MNEMONIC environment variable

Fix the algorand login example script

---

imsv-docs-astro/markdoc.config.mjs
imsv-docs-astro/src/content/docs/guides/authentication/authentication.mdoc
imsv-docs-astro/tailwind.config.ts
imsv-docs-astro/typography.ts

Ticket Link: https://www.notion.so/immersve/Table-captions-6f330d10e9084b5c9fac792a4bb5dfdf?pvs=4

Add table captions

---

imsv-docs-astro/src/content/docs/guides/card-issuing-apps/web3-wallet-card-issuing-integration.mdoc
imsv-docs-astro/src/content/docs/guides/regions.mdoc
imsv-docs-docusaurus/openapi/endpoints/supported-regions/get-supported-regions.yaml
imsv-docs-docusaurus/openapi/endpoints/supported-regions/models/get-supported-regions-response.yaml
imsv-docs-docusaurus/openapi/immersve.yaml

- Added API reference for regions endpoint
- Updated the supported regions guide to reflect that the list of regions is not static but dynamic
Ticket Link: https://www.notion.so/immersve/Update-Documentation-c32451f8a8e943af9123e39fb169bd54?pvs=4

Feature: Regions API docs

---

imsv-docs-astro/src/content/docs/guides/authentication/algorand-login.mdoc
imsv-docs-astro/src/content/docs/guides/authentication/authentication.mdoc
imsv-docs-astro/src/content/docs/guides/authentication/siwe-login.mdoc
imsv-docs-astro/src/content/docs/guides/authentication/xrpl-login.mdoc
imsv-docs-docusaurus/openapi/endpoints/login/login-init.yaml
imsv-docs-docusaurus/openapi/endpoints/login/models/algorand-login-request.yaml
imsv-docs-docusaurus/openapi/endpoints/login/models/siwe-login-request.yaml
imsv-docs-docusaurus/openapi/endpoints/login/models/xrpl-login-request.yaml

Document autoSignup request option for login-init endpoint
Ticket Link: [Notion task](https://www.notion.so/immersve/Update-login-init-API-ref-docs-e81bf985eced45c4921e2a4e132a9292?pvs=4)

Add login-init autoSignup parameter to docs

---

starlight/components/imsv/Header.astro

The animation is visible when switching to dark mode.

Remove ugly header animation

---

imsv-docs-astro/public/postman/public-sandbox-environment.json
imsv-docs-astro/src/content/docs/resources/public-sandbox-account.mdoc

Ticket: https://immersve.slack.com/archives/C06G54VDLM8/p1724028973282039

Use localhost:3000 instead of localhost:80 for allowed origin on partner sandbox acct

---

imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel-params/algorand.yaml
imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel-params/universal-evm.yaml
imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel.yaml

Documenting params for funding channel creation.
https://431-merge--jovial-scone-ec740d.netlify.app/api-reference/create-a-funding-channel/

Adding algorand type funding channel params

---

yarn.lock

update elliptic dependency

---

imsv-docs-astro/src/content/docs/guides/supported-tokens/supported-tokens.mdoc

Fixing a typo in description.
Ticket Link: https://immersve.slack.com/archives/C06G54VDLM8/p1724626767787499?thread_ts=1724560993.998009&cid=C06G54VDLM8

Update supported tokens description

---

starlight/components/imsv/Footer.astro

Ticket Link: https://www.notion.so/immersve/Style-Improvement-prev-next-page-max-width-justify-5fa4d7ce2a1b44fb9de8a1eeb4194b29?pvs=4

Improve whitespace around footer next link

---

imsv-docs-astro/src/content/docs/guides/supported-chains/arbitrum.mdoc
imsv-docs-astro/src/content/funding-types/arbitrum-mainnet-usdc-universal-evm.md
imsv-docs-astro/src/content/funding-types/arbitrum-sepolia-usdc-universal-evm.md
imsv-docs-astro/src/content/network-tokens/usdc-arbitrum-mainnet.md
imsv-docs-astro/src/content/network-tokens/usdc-arbitrum-sepolia.md
imsv-docs-astro/src/content/networks/arbitrum-mainnet.md
imsv-docs-astro/src/content/networks/arbitrum-sepolia.md
imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel.yaml

Adding Arbitrum network details
Ticket Link: https://www.notion.so/immersve/arbitrum-network-and-funding-types-public-docs-ece4da935c2f439182ef8333245ccd5b?pvs=4

Adding arbitrum network and funding types

---

imsv-docs-docusaurus/openapi/endpoints/login/models/create-challenge-request.yaml
imsv-docs-docusaurus/openapi/endpoints/login/models/create-challenge-response.yaml
imsv-docs-docusaurus/openapi/endpoints/login/models/siwe-login-request.yaml

Ticket Link: https://immersve.slack.com/archives/C06FZAC49EC/p1725564411476899

Add missing arbitrum network to auth endpoints

---

imsv-docs-docusaurus/openapi/endpoints/cards/models/card.yaml

Add cardProgramId and region in the card's model
Ticket Link: [_link_here_](https://www.notion.so/immersve/add-programId-and-regionCode-in-card-s-api-response-1051d446ed8a8022bdc8dd51e4e6bc9d?pvs=4)
PR to rename region to regionCode in card's response in amethyst: [__here__](https://github.com/immersve/amethyst/pull/2362)

feature(multi-regional):add cardProgramId and region in card's model

---

imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel.yaml
imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/funding-channel.yaml
imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/funding-source.yaml

Documenting purpose for funding sources and channels.
https://449-merge--jovial-scone-ec740d.netlify.app

Purpose for funding channel and source

---

imsv-docs-docusaurus/openapi/endpoints/funding-sources/create-funding-source.yaml

Fix typo in Funding Source doc

---

imsv-docs-astro/src/content/docs/guides/funding-protocols/custodial-funding-protocol.mdoc
imsv-docs-astro/src/content/docs/guides/testing/payment-simulator.mdoc

Fired up the spellchecker and this is what it found.

Fixing some typos

---

imsv-docs-astro/src/content/docs/guides/funding-protocols/custodial-funding-protocol.mdoc

Ticket Link: https://www.notion.so/immersve/describe-responsibilities-for-each-message-type-1051d446ed8a805f80a3cd6bbb805f8b?pvs=4

Add custodial message type descriptions

---

imsv-docs-astro/src/content/docs/guides/funding-protocols/custodial-funding-protocol.mdoc

Ticket Link: https://www.notion.so/immersve/change-payment-currency-to-usdc-1101d446ed8a8089a72ec219b4786ec3?pvs=4

Use USDC for custodial payment amount

---

imsv-docs-astro/src/content/docs/guides/funding-protocols/custodial-funding-protocol.mdoc

Ticket Link: https://www.notion.so/immersve/Support-Incremental-Auth-1121d446ed8a80849b91f4bc0629cb1d?pvs=4

Document custodial incremental auth scenario

---

imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/funding-source.yaml

externalId and network were added.
https://immersve.slack.com/archives/C04EDU7MYCB/p1728403056461999

Funding source - update response schema

---

imsv-docs-astro/src/content/docs/guides/funding-protocols/custodial-funding-protocol.mdoc

Ticket Link: https://www.notion.so/immersve/Document-event-type-names-1191d446ed8a80ff8368e6b04990131b?pvs=4

Add event types to custodial protocol body spec

---

imsv-docs-docusaurus/openapi/endpoints/simulator/authorize.yaml
imsv-docs-docusaurus/openapi/endpoints/simulator/models/authorize-request.yaml

Functionality: https://github.com/immersve/amethyst/pull/2458
Ticket Link: https://www.notion.so/immersve/Incremental-auth-simulator-docs-11b1d446ed8a806aa810efa74605ccd4?pvs=4

Feature: Add incremental-auth support to simulator

---

starlight/components/imsv/Footer.astro
starlight/components/imsv/Header.astro

Ticket Link: https://www.notion.so/immersve/Change-support-href-to-immersve-com-contact-1161d446ed8a800c8089d6775ff3f5d1?pvs=4

Change support links to use marketing site contact form

---

imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel-params/custodial.yaml
imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel-params/simulator.yaml
imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel-params/universal-evm.yaml
imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel.yaml
imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/funding-channel.yaml

API Update: https://github.com/immersve/amethyst/pull/2477

Funding Channel request and response for custodial type

---

imsv-docs-astro/src/content/docs/guides/funding-protocols/custodial-funding-protocol.mdoc

Add custodial decline messages to Custodial Funding Protocol
Ticket Link: https://www.notion.so/immersve/Publish-spec-to-docs-1201d446ed8a80759c97efa09361d621?pvs=4

Add custodial decline messages

---

imsv-docs-astro/src/content/docs/guides/funding-protocols/custodial-funding-protocol.mdoc

Ticket Link: https://www.notion.so/immersve/Publish-spec-to-docs-1201d446ed8a80759c97efa09361d621?pvs=4

Custodial webhook decline messages explained

---

imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc

Adds the contract detail info as optional step for IC KYC.
Ticket Link: https://immersve.slack.com/archives/C06MGUX55L6/p1729194615408009

add contact details info as optional step for immersve conducted kyc

---

imsv-docs-astro/src/content/docs/guides/funding-protocols/custodial-funding-protocol.mdoc

Update merchantCountryCode example and description 
Ticket Link:  https://www.notion.so/immersve/Update-docs-1261d446ed8a8055ba7afc5f6e4e20f3?pvs=4
Test plan: Check the docs

update merchantCountryCode example and description

---

imsv-docs-docusaurus/openapi/endpoints/transactions/list-payment-notifications.yaml
imsv-docs-docusaurus/openapi/endpoints/transactions/models/list-payment-notifications-result.yaml
imsv-docs-docusaurus/openapi/endpoints/transactions/models/payment-notification.yaml
imsv-docs-docusaurus/openapi/immersve.yaml

API details: https://www.notion.so/immersve/API-to-list-custodial-webhook-deliveries-42b57e840286411d8e0f15852faf7827
Notion Design: https://www.notion.so/immersve/List-Payment-Notifications-by-Account-Id-11f1d446ed8a806bb3b5f2f2020a9d3b
Ticket Link: https://www.notion.so/immersve/Public-documentation-1211d446ed8a806cbcffcb02f8036ccd?pvs=4

Adding list payment notifications api docs

---

imsv-docs-docusaurus/openapi/endpoints/transactions/models/list-payment-notifications-result.yaml

Ticket Link: https://immersve.slack.com/archives/C07HU5LGYSU/p1730257262296749?thread_ts=1730242245.403349&cid=C07HU5LGYSU

Adding pageInfo model for list payment notifications pagination

---

imsv-docs-docusaurus/openapi/endpoints/transactions/models/transaction-detail-extension.yaml
imsv-docs-docusaurus/openapi/endpoints/transactions/models/transaction.yaml

Some of it was already removed in code.
The rest is removed here https://github.com/immersve/amethyst/pull/2505

Removing on chain information from transactions

---

imsv-docs-docusaurus/openapi/endpoints/simulator/clear.yaml
imsv-docs-docusaurus/openapi/endpoints/simulator/models/clear-request-base.yaml
imsv-docs-docusaurus/openapi/endpoints/simulator/models/clear-request.yaml

Ticket Link: https://www.notion.so/immersve/update-api-docs-13a1d446ed8a805a9816ea235411ad0a?pvs=4

Feature: Simulator - Multiple clearing support

---

imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc
imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
imsv-docs-docusaurus/openapi/models/kyc-params.yaml

Update Immersve docs to reflect the change in Spending prereqs response.
Ticket Link: https://www.notion.so/immersve/Update-Immersve-docs-to-reflect-the-change-in-Spending-prereqs-response-13f1d446ed8a80e6b620e2d40e61cf2d

Feature: Spending Prerequisites: Add kyc rejection reasons to response

---

imsv-docs-docusaurus/openapi/endpoints/kyc/models/retrieve-kyc-statement-response.yaml
imsv-docs-docusaurus/openapi/endpoints/kyc/models/submit-kyc-statement-request.yaml

To be more clear about how it's meant to be used
Ticket Link: https://immersve.slack.com/archives/C04UUJR3G2X/p1731607200382849

Improve description of idempotency key

---

imsv-docs-docusaurus/openapi/endpoints/kyc/get-kyc-profile.yaml

Remove override of auth schemes.
Ticket Link: https://immersve.slack.com/archives/C04EDU7MYCB/p1731670953224319

Get KYC Profile - remove security override

---

imsv-docs-docusaurus/openapi/endpoints/kyc/models/get-kyc-profile-response.yaml

Ticket Link: https://immersve.slack.com/archives/C04EDU7MYCB/p1731670953224319

Get KYC Profile: status enumeration

---

imsv-docs-docusaurus/openapi/endpoints/accounts/models/account.yaml

update to add "version" and "liveness" variables to response schema within api-docs for create account.

create account api-doc update

---

imsv-docs-docusaurus/openapi/endpoints/accounts/models/account.yaml

Reverts immersve/immersve-docs#536

Revert "create account api-doc update"

---

imsv-docs-docusaurus/openapi/endpoints/accounts/models/account.yaml

update to add "version" and "liveness" variables to response schema within api-docs for create account.

add version and liveness to create account

---

imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc

Rephrased parts of doc for better understandability for non-experienced readers
Ticket Link: (https://www.notion.so/immersve/Improve-error-logs-and-product-metrics-13b1d446ed8a80339c6ac14c0ee2bb8f?pvs=4)

Updated Immersve conducted KYC doc for clarity

---

imsv-docs-docusaurus/openapi/endpoints/prerequisites/models/get-spending-prerequisite-response.yaml
imsv-docs-docusaurus/openapi/endpoints/prerequisites/spending-prerequisites.yaml

* Hide deprecated "type" field
* Remove "depositAndLock"
* Move AML stage to last position

Cleanup prerequisites example

---

imsv-docs-docusaurus/openapi/endpoints/transactions/models/transaction.yaml

Fixing the transaction status name to match amethyst code
Ticket Link: https://immersve.slack.com/archives/C07HU5LGYSU/p1732610956099629

Transaction status name fix

---

imsv-docs-docusaurus/openapi/endpoints/transactions/get-payment-notification.yaml
imsv-docs-docusaurus/openapi/immersve.yaml

Adding get payment notification endpoint.
Ticket Link: https://www.notion.so/immersve/document-1501d446ed8a80b6875dd45ab0507657?pvs=4
Deployment: http://560-merge--jovial-scone-ec740d.netlify.app

Get payment notification endpoint

---

imsv-docs-astro/src/content/docs/guides/funding-protocols/custodial-funding-protocol.mdoc

Custodial refund must be credited on non final payment advice.
Ticket Link: https://www.notion.so/immersve/1531d446ed8a80808218da90eb96bd53

Fix custodial refund obligations

---

imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc

Structured Address and Unstructured Address in Partner-Conducted KYC
Ticket Link: https://www.notion.so/immersve/Documentation-clarify-structured-Unstructured-address-13b1d446ed8a806c8a35ff29b43a23eb

feat(kyc): Structured Address and Unstructured Address in Partner-Conducted KYC

---

imsv-docs-astro/src/content/docs/guides/testing/payment-simulator.mdoc

Ticket Link: https://immersve.slack.com/archives/C06G54VDLM8/p1734307820280269

remove reference to metamask

---

imsv-docs-docusaurus/openapi/endpoints/transactions/models/transaction.yaml

Ticket Link: https://immersve.slack.com/archives/C06G54VDLM8/p1734322709927919

Improve fee amount description on get transaction API reference page

---

imsv-docs-astro/src/content/docs/guides/regions.mdoc

On supported regions page.
Ticket Link: https://immersve.slack.com/archives/C06G54VDLM8/p1735596039517199

Correct spelling for Brazil

---

imsv-docs-docusaurus/openapi/endpoints/simulator/authorize.yaml
imsv-docs-docusaurus/openapi/endpoints/simulator/models/authorize-request.yaml

[API Design](https://www.notion.so/immersve/Submit-Simulator-Authorization-7d406f9402b44b5d86b4bb4d205e9f84)
Ticket Link: https://www.notion.so/immersve/Document-simulator-force-post-auth-17a1d446ed8a80548737f391d1be4e76?pvs=4

Document force post authorizations

---

yarn.lock

Fix for https://github.com/immersve/immersve-docs/security/dependabot/88

upgrade vitest

---

imsv-docs-astro/src/content/docs/use-cases/_non-custodial-how-it-works.mdoc

* Prefer "funds" over "stablecoins".
* Mention approvals as well as deposit/withdraw.

Improve language for non-custodial "how it works"

---

imsv-docs-docusaurus/openapi/endpoints/transactions/transactions-list.yaml

Documents a field added to allow filtering by transaction status.
Related code change: https://github.com/immersve/amethyst/pull/3083
Ticket Link: https://immersve.slack.com/archives/C085XJSV6AV/p1736391357304449

Add statuses filter to transaction list endpoint

---

imsv-docs-docusaurus/openapi/endpoints/supported-regions/get-supported-regions.yaml
imsv-docs-docusaurus/openapi/endpoints/supported-regions/models/get-supported-regions-response.yaml

adds `documents` to get supported regions api
ticket link: https://www.notion.so/immersve/Public-docs-update-19a1d446ed8a80788f37c7b19280d889?pvs=4

Feat(PRD) Add documents to get supported regions

---

imsv-docs-docusaurus/openapi/endpoints/supported-regions/models/document.yaml
imsv-docs-docusaurus/openapi/endpoints/supported-regions/models/get-supported-regions-response.yaml

ticket link:https://www.notion.so/immersve/Docs-for-updated-structure-1a51d446ed8a809db79bd465fefc707e?pvs=4

feat(prd)- Supported Regions Document spec update

---

imsv-docs-astro/src/content/docs/guides/card-issuing-apps/legal-document-requirements.mdoc
imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
imsv-docs-astro/src/content/docs/guides/regions.mdoc
imsv-docs-docusaurus/openapi/endpoints/supported-regions/get-supported-regions.yaml

ticket link: https://www.notion.so/immersve/update-supported-regions-guide-1a61d446ed8a8008b007f7cdbf1f0b12?pvs=4

Feat(prd) Add guidelines for displaying legal docs for partners

---

imsv-docs-astro/src/content/docs/guides/core-concepts/card-lifecycle.mdoc
imsv-docs-docusaurus/openapi/endpoints/cards/card-unfreeze.yaml

Update card lifecycle doc to support freeze/unfreeze card, also change the language of UNFREEZE_NOT_ALLOWED.
Ticket Link: https://www.notion.so/immersve/write-a-paragraph-or-more-on-freeze-1ad1d446ed8a803ca521ebfdedfb0c83?pvs=4

Update card lifecycle doc to support freeze/unfreeze card

---

imsv-docs-docusaurus/openapi/endpoints/accounts-custodial/account-cancel-custodial.yaml
imsv-docs-docusaurus/openapi/endpoints/accounts-custodial/account-single-custodial.yaml
imsv-docs-docusaurus/openapi/endpoints/cards/card-activate-custodial.yaml
imsv-docs-docusaurus/openapi/endpoints/cards/card-cancel.yaml
imsv-docs-docusaurus/openapi/endpoints/cards/card-close-custodial.yaml
imsv-docs-docusaurus/openapi/endpoints/cards/card-freeze.yaml
imsv-docs-docusaurus/openapi/endpoints/cards/card-get-custodial.yaml
imsv-docs-docusaurus/openapi/endpoints/cards/card-get-secure-custodial.yaml
imsv-docs-docusaurus/openapi/endpoints/cards/card-set-pin.yaml
imsv-docs-docusaurus/openapi/endpoints/cards/card-unfreeze.yaml
imsv-docs-docusaurus/openapi/immersve.yaml
imsv-docs-docusaurus/openapi/models/account-id-path.yaml
imsv-docs-docusaurus/openapi/models/card-id-path.yaml

This helps tools like openapi-format to correctly identify the common types.
Original change request: https://github.com/immersve/immersve-docs/pull/619

Convert common parameter models to OpenAPI components

---

imsv-docs-docusaurus/openapi/models/api-error-400.yaml

Update 400 error to match the structure changed in [this PR ](https://github.com/immersve/amethyst/pull/3343)
Ticket Link:  https://www.notion.so/immersve/Explore-reproduce-Vield-case-and-see-if-path-can-be-improved-1ac1d446ed8a80369b85f88a3f1aedc8
deploy URL: https://625-merge--jovial-scone-ec740d.netlify.app/api-reference/submit-kyc-statement/

Update 400 error

---

imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc
imsv-docs-docusaurus/openapi/endpoints/residential-addresses/get-residential-addresses.yaml
imsv-docs-docusaurus/openapi/endpoints/residential-addresses/models/residential-addresses-response.yaml
imsv-docs-docusaurus/openapi/endpoints/residential-addresses/models/structured-address-request.yaml
imsv-docs-docusaurus/openapi/endpoints/residential-addresses/models/structured-address-response.yaml
imsv-docs-docusaurus/openapi/endpoints/residential-addresses/models/unstructured-address-request.yaml
imsv-docs-docusaurus/openapi/endpoints/residential-addresses/submit-residential-addresses.yaml
imsv-docs-docusaurus/openapi/immersve.yaml

1. Get Residential Addresses
2. Submit Residential Addresses
3. IC KYC Guide Update (more updates are coming with @forktrucka's PR https://github.com/immersve/immersve-docs/pull/622)
Ticket Link: https://www.notion.so/immersve/Update-the-docs-18b1d446ed8a80e4ac4fc967b7589812

Add residential addresses endpoints to the API reference and update IC KYC

---

imsv-docs-astro/src/components/icons/Browser.astro
imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc
imsv-docs-docusaurus/openapi/endpoints/prerequisites/models/get-spending-prerequisite-request.yaml
imsv-docs-docusaurus/openapi/endpoints/prerequisites/models/get-spending-prerequisite-response.yaml
imsv-docs-docusaurus/openapi/models/expected-spend-amount-params.yaml

Adds a how it works section explaining Spending Prereq stages.
Adds missing spending prereq property values.
Ticket Link: https://www.notion.so/immersve/Update-the-docs-18b1d446ed8a80e4ac4fc967b7589812

add overview of Immersve Conducted KYC process

---

imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/funding-channel.yaml

Add funding mode to funding channel endpoint docs 
Ticket Link: https://www.notion.so/immersve/Add-docs-1bd1d446ed8a803ca531e1c9c51ac53a?pvs=4

Add mode to funding channel

---

imsv-docs-astro/src/components/registry-views/protocols/FundingProtocolsTable.astro
imsv-docs-astro/src/content/docs/guides/funding-protocols/funding-protocols.mdoc
imsv-docs-astro/src/models/FundingProtocol.mjs

Add available protocols section to Funding Protocols page.

Add available funding protocols list

---

imsv-docs-astro/src/content/docs/guides/funding-protocols/funding-protocols.mdoc
imsv-docs-astro/src/content/docs/guides/funding-protocols/simulator-funding-protocol.mdoc

Simulator protocol is classified as a deposit variant.

Improve protocol variant descriptions

---

imsv-docs-astro/src/content/docs/guides/kyc/kyc-spending-prerequisites.mdoc

Tidy up line wrapping of kyc prerequisites examples

Tidy up line wrapping of kyc prerequisites examples

---

yarn.lock

Fixes:
- https://app.snyk.io/org/immersve/project/9ae05c94-f95f-4b38-aaf3-0ae105ccdeff#issue-SNYK-JS-VITE-9653016
- https://app.snyk.io/org/immersve/project/9ae05c94-f95f-4b38-aaf3-0ae105ccdeff#issue-SNYK-JS-VITE-9919777
- https://app.snyk.io/org/immersve/project/9ae05c94-f95f-4b38-aaf3-0ae105ccdeff#issue-SNYK-JS-VITE-9685035

upgrade vite to latest to fix vulnerability

---

imsv-docs-docusaurus/openapi/endpoints/file-uploads/models/upload-file-response.yaml
imsv-docs-docusaurus/openapi/endpoints/file-uploads/upload-file.yaml
imsv-docs-docusaurus/openapi/immersve.yaml

Add the docs for the file upload endpoint
- Add doc for post request
Ticket Link: https://www.notion.so/immersve/public-api-docs-for-download-and-upload-endpoint-1de1d446ed8a80249e5ff3dcf0dfc2a3?pvs=4

Add file upload endpoint to public docs

---

imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
imsv-docs-docusaurus/openapi/endpoints/regions/models/get-supported-regions-response.yaml

Ticket Link: https://www.notion.so/immersve/update-the-docs-with-the-unstructured-address-supported-countries-list-1e41d446ed8a80f4848bf0bbcf370cda?source=copy_link

Region unstructured address flag

---

imsv-docs-docusaurus/docusaurus.config.js
starlight/components/imsv/Header.astro

Theme selection is automatic based on user agent preference.

Disable explicit theme selection

---

imsv-docs-astro/astro.config.mjs

Move API Reference link to top of side nav for discoverability on mobile. Contact link is added to bottom of side nav.

Improve side nav key links

---

imsv-docs-astro/src/content/docs/guides/testing/passing-kyc-in-test.mdoc

Ticket Link: https://www.notion.so/immersve/Update-docs-for-partner-conducted-testing-to-generate-low-risk-data-26c1d446ed8a80e1b981c9b3f9b30528

Testing Partner Conducted KYC: Add age constraints
