- openapi/endpoints/login/models/challenge-request.yaml
make url a required field on [docs.immersve.com](http://docs.immersve.com/) on the generate challenge endpoint. Also specify that we validate this url against allowedOrigin of the client application.
Ticket Link:https://www.notion.so/immersve/SIWE-Auth-flow-changes-798d84a6335d40c0b0b31facd78c00ae?pvs=4
> make url a required field in the SIWE challenge endpoint

- openapi/endpoints/kyc/models/ADDRESS.yaml
These were missed in the initial cut.
**Test Plan:**
> Add suburb and town to KYC address spec

- docs/redirects/accounts-custodial.mdx
- docs/redirects/activate-card-custodial.mdx
- docs/redirects/block-card-custodial.mdx
- docs/redirects/cancel-account-custodial.mdx
- docs/redirects/cards-custodial.mdx
- docs/redirects/close-card-custodial.mdx
- docs/redirects/create-account-custodial.mdx
- docs/redirects/create-card-custodial.mdx
- docs/redirects/get-account-custodial.mdx
- docs/redirects/get-card-custodial.mdx
- docs/redirects/get-secure-card-custodial.mdx
- docs/redirects/set-pin-card-custodial.mdx
- docs/redirects/unblock-card-custodial.mdx
- docs/redirects/update-account-custodial.mdx
- openapi/immersve.yaml
All old links redirect.
Custodial guide remains the same. It does talk about capability on physical cards that is potentially unsupported. 
Webhook guide remains the same.
Ticket Link: [_link_here_](https://www.notion.so/immersve/Remove-custodial-endpoints-from-API-docs-a097703b09504d1f92ad14fd1e8277ff)
> Remove custodial api references

- openapi/endpoints/accounts/accounts-list.yaml
- openapi/endpoints/accounts/models/account.yaml
- openapi/endpoints/accounts/models/list-accounts-response.yaml
- openapi/immersve.yaml
get `/api/accounts` did not have documentation. This PR adds documentation for that endpoint
https://www.notion.so/immersve/502cdbbdaf8b476aa8c579cd6750f008?v=c53f7cd0734044ed981ebd4cfc173ed1&p=c3b4adc486e44ac3b927b2a385f8caf5&pm=s
> list accounts endpoint documentation

- openapi/endpoints/login/models/login-request.yaml
- openapi/endpoints/login/models/login-response.yaml
Notion design: https://www.notion.so/immersve/Login-with-signed-SIWE-challenge-c3ef47fcd44945daa30569d3690928fd
Change to:
- Add autoCreateCardholderAccount flag to login request
- Add cardholderAccountId to login response
Test plan: Expect to see described changes in SIWE login docs.
Ticket: [📖 Trust Wallet Integration Guide](https://www.notion.so/immersve/Trust-Wallet-Integration-Guide-62a09f79498c4bf780922e61b949ed26)
> 📝 Add flag for cardholder account creation during SIWE login

- docs/guides/card-lifecycle.md
- docs/redirects/api-reference/assets-category.mdx
- docs/redirects/api-reference/card-cancel-asynchronously.mdx
- openapi/endpoints/assets/asset-balance-get.yaml
- openapi/endpoints/cards/card-cancel.yaml
- openapi/endpoints/cards/card-order.yaml
- openapi/immersve.yaml
Deprecates card-order and get-wallet-balance endpoints.
Updates category titles and api-reference titles.
Go commit-by-commit
[Ticket Link: _link_here_](https://www.notion.so/immersve/Official-Docs-Make-over-8d9657798cdf43079e541a903ae09e0f)
> Deprecate endpoints

- openapi/endpoints/prerequisites/models/get-spending-prerequisite-response.yaml
- openapi/endpoints/prerequisites/spending-prerequisites.yaml
- openapi/models/kyc-params.yaml
The spending prerequisites endpoint should show when KYC is required for a card to be issued. Change to add KYC response in Spending Prerequisites endpoint.
🎨 [Notion Design](https://www.notion.so/Spending-prerequisites-b20c4914ca0346069504ecf6428bcdd8) 
📖 [Ticket Link](https://www.notion.so/immersve/Create-KYC-Check-09d981c97d5c48b9822eec8d4edb59df?pvs=4)
Test plan: Expect to see KYC prerequisites as per screenshot.
> 📝 Add KYC requirements to Spending Prerequisites Endpoint

- openapi/endpoints/kyc/models/retrieve-kyc-statement-response.yaml
- openapi/endpoints/kyc/models/submit-kyc-statement-request.yaml
- openapi/endpoints/kyc/retrieve-partner-kyc-statement.yaml
- openapi/endpoints/kyc/submit-partner-kyc-statement.yaml
- openapi/immersve.yaml
Retrieve KYC statement endpoint.
Removed timestamp from submit endpoint as this was never implemented.
**Note:** There is a PR up at the moment which adds an API response to the submit endpoint, this is still being decided on so have left it out of this PR for now but can add if need be.
Ticket Link: https://www.notion.so/immersve/Get-Partner-KYC-Statement-f655cd556aa34ba89064bb13b8fb5a70
**Test Plan:**
> Retrieve KYC statement endpoint

- docs/guides/complete-headless-kyc-checks.md
- openapi/endpoints/kyc/models/get-kyc-profile-response.yaml
- openapi/endpoints/prerequisites/spending-prerequisites.yaml
Added complete headless KYC guide.
Ticket Link: https://www.notion.so/immersve/Create-guide-in-the-docs-immersve-com-3510b1d8ab7f432fa4bb080ce7ec2c6f?pvs=4
Test plan:
> Add complete headless kyc guide

- docs/guides/card-funding.md
Passed through Hemingway and re-wrote the first section for readability.
Made clear that a funding source is 1:1 with cardholder.
Ticket Link: https://www.notion.so/immersve/Update-the-docs-to-explicitly-explain-that-a-USER-and-FUNDING-SOURCE-are-1-1-b9bde1de8c904edba7c53bb167cf46b9?pvs=4
> Make funding guide more readable

- .prettierrc.js
The repo is currently using a mix of single and double quotes. We are standardising to double quotes for YAML.
Ticket Link: https://immersve.slack.com/archives/C03471T0RMF/p1693456104685509?thread_ts=1693453548.763679&cid=C03471T0RMF
> chore(prettier-config): Change prettier config to double quotes for YAML

- openapi/endpoints/funding-sources/funding-source-interactions-get.yaml
change endpoint name to `List Funding Source Interactions`
> (fix)Funding Source Interactions name

- openapi/endpoints/client-application/client-application-update-origins.yaml
- openapi/endpoints/client-application/models/client-application-update-origins-request.yaml
- openapi/immersve.yaml
This endpoint can now be used by accounts with account-owner role.
Ticket Link: https://www.notion.so/immersve/Make-updateAllowedOrigins-endpoint-self-service-2f1effcc2bb64846993fabc084c10161?pvs=4
> Feature - Add endpoint for updating client application allowed origins

- openapi/endpoints/funding-sources/models/funding-source-interaction.yaml
a card transaction doesnt have transaction hash and block number.
> (fix) funding source interaction example

- docs/guides/universal-evm-smart-contract.md
* Prevent breaks in token code -- on reduced screen size the "IMMUSDC" is getting wrapped which is very ugly.
* Display contract address in block explorer link -- enables copy pasting the address without navigating to polygonscan.
> Improve Universal EVM contract table

- .github/workflows/test-deploy.yml
- .gitignore
- scripts/github-deploy-summary.sh
- scripts/netlify-deploy.sh
The site gets deployed to https://${branch}--jovial-scone-ec740d.netlify.app/. Note that in a Github PR the branch name is the PR number not the feature branch name. Example:
https://181-merge--jovial-scone-ec740d.netlify.app/
This deployment URL is discoverable in the actions pipeline and step summaries.
The Netlify subscription is a free single-user plan for admin@immersve.com. Credentials are in 1Password engineering admin vault. The NETLIFY_TOKEN env var expires in November.
> Publish site to netlify for preview

- .github/workflows/deploy.yml
- scripts/github-build-info.mjs
Include build-info.json in build output. Later this info should be included in the footer of every page but for now just include the raw data so we can find out what version is deployed.
The build number logic is changed compared to all other repositories so that it includes the run attempt and unique build id as suffixes.
> Build info

- CODEOWNERS
Master branch protection rules have been changed to require approval from codeowners file. The docs-approvers group includes Kira, Nic, Braden and Nathan.
> Set docs-approvers group as codeowners

- imsv-docs-astro/astro.config.mjs
This fixes rendering of the `<sup>` tag in index.mdoc.
> Allow html within markdoc files

- imsv-docs-astro/src/redirects.yml
The immersve.com marketing site currently links to the docusaurus-generated api-reference category page which was relocated when moving content to Astro.
> Add missing /category/api-reference redirect

- imsv-docs-docusaurus/openapi/models/smart-contract-write-params.yaml
Fixed incorrect schema type for spending prerequisites
Was
```
"abi": {
"type": "function",
"name": "approve",
// ...
}
```
Became (this is what our endpoint returns) (example "not from schema" is correct)
```
"abi": [{
"type": "function",
"name": "approve",
// ...
}]
```
Ticket Link: NA
Test plan:
Compare schema with real response
> fix(spending-prerequisites): Abi schema type

- imsv-docs-astro/astro.config.mjs
- imsv-docs-astro/markdoc.config.mjs
- imsv-docs-astro/src/components/FundingContractsTable.astro
- imsv-docs-astro/src/content/config.ts
- imsv-docs-astro/src/content/docs/guides/funding-protocols/universal-evm-smart-contract.mdoc
- imsv-docs-astro/src/content/docs/resources/smart-contracts.mdoc
Add smart contract links page in a new "resources" top-level docs section. The smart contract links are generated automatically based on the "source" attribute on the funding-protocol content frontmatter.
> Add smart contract resources

- imsv-docs-docusaurus/openapi/endpoints/transactions/transactions-list.yaml
Verb method is incorrect.
Actual route:
```
const method = 'get';
```
> Fix - List Transactions verb error

- imsv-docs-docusaurus/openapi/immersve.yaml
List transactions and List Cards route paths do not conform to our [API endpoint definition guidelines](https://www.notion.so/immersve/API-Endpoint-definition-Guideline-007757155c9544c39e2c22e717b82d35).
The original route path has been updated to follow our conventions. An alias to support the original path has been added.
Amethyst PRs:
https://github.com/immersve/amethyst/pull/1468
https://github.com/immersve/amethyst/pull/1470
Ticket Link: https://www.notion.so/immersve/Remove-legacy-route-aliases-0b9b3b0a7a764683a8f512f7665f9d6a
Slack thread: https://immersve.slack.com/archives/C03471T0RMF/p1707940650144559
> Fix -  list-funding-channels & list-cards paths

- imsv-docs-astro/src/content/docs/guides/authentication.mdoc
- imsv-docs-docusaurus/openapi/endpoints/login/models/challenge-request.yaml
Decision was made that as part of Refresh Token Epic we will begin removing support for scopes other than `cardholder-partner` because these other scopes provide more access than any existing users of the platform need. This is step1: remove mention of other scopes from our docs. Step2 will involve tracking and contacting customers that are using outdated scopes (such as full-access) and getting them to stop using these, and finally step3 will be to deprecate the unneeded scopes from the code.
Ticket Link: Notion Task[_link_here_](https://www.notion.so/immersve/Update-docs-to-remove-scopes-other-than-cardholder-partner-a4393bb1402445a19b56187ac207ed4b?pvs=4)
Test plan: manually check that mentions of scopes other than cardholder-partner are gone from docs.immersve.com (previous scopes to …
> Remove mention of all authentication scopes other than `cardholder-partner`

- imsv-docs-docusaurus/openapi/endpoints/funding-sources/create-funding-source.yaml
Docs were saying we return an empty object, which is just wrong.
> Create funding source endpoint was missing return info

- imsv-docs-astro/astro.config.mjs
- imsv-docs-astro/src/content/docs/guides/http-status-codes.mdoc
Adds a guide inspired by [Centrapay's guide](https://docs.centrapay.com/api/http-status-codes/) but with the use of different wording.
Ticket Link: this is an [action item](https://www.notion.so/immersve/Get-HTTP-status-codes-documented-similar-to-https-docs-centrapay-com-api-http-status-codes-d408f9f47b3e408f8aa9a6e31cbbb795?pvs=4) from tech catch up 
doc design entry: https://www.notion.so/immersve/Docs-Content-Design-858f8fda3f1442ea82f8ddc8f007d792?p=28634570a3ec42e09d4a282541a24801&pm=s
> Add HTTP Status Codes guide

- imsv-docs-astro/src/styles/tailwind.css
The styling of headers was looking off. So I commented out tailwind classed. Could not find any downside of doing that 
Ticket Link: just noticed this is not looking good
> fix: comment out tailwind styling for headers

- imsv-docs-astro/markdoc.config.mjs
- imsv-docs-astro/src/components/Link.astro
- imsv-docs-astro/src/content/docs/guides/card-issuing-apps/add-card-to-xpay-wallet.mdoc
- imsv-docs-astro/src/content/docs/guides/card-issuing-apps/creating-a-funding-channel.mdoc
- imsv-docs-astro/src/content/docs/guides/card-issuing-apps/custodial-on-chain-card-issuing-integration.mdoc
- imsv-docs-astro/src/content/docs/guides/core-concepts/card-payments-101.mdoc
- imsv-docs-astro/src/content/docs/guides/funding-protocols/funding-protocols.mdoc
- imsv-docs-astro/src/content/docs/guides/funding-protocols/universal-evm-funding-protocol.mdoc
- imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc
- imsv-docs-astro/src/content/docs/guides/kyc/introduction.mdoc
- imsv-docs-astro/src/content/docs/guides/supported-chains/ethereum.mdoc
- imsv-docs-astro/src/content/docs/guides/supported-chains/polygon.mdoc
- imsv-docs-astro/src/content/docs/guides/supported-chains/supported-chains.mdoc
- imsv-docs-astro/src/content/docs/guides/supported-tokens/usdc.mdoc
Add page link support to the link component. Linked pages have the title set automatically and provide fast feedback (ie throw an error) when the page does not exist.
> Add auto page link

- README.md
- imsv-docs-docusaurus/openapi/immersve.yaml
This change allows generating the self-contained OpenAPI specification file by fixing the OpenAPI version.
Ticket Link: discussion started in this thread https://immersve.slack.com/archives/C06BAC49Y81/p1714952775052809
> fix: use 3.1.0 so swagger-codegen works and add an instruction to the README

- .gitignore
- imsv-docs-astro/markdoc.config.mjs
- imsv-docs-astro/src/components/Warning.astro
- imsv-docs-astro/src/components/icons/WarningIcon.astro
- imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
- imsv-docs-docusaurus/openapi/endpoints/kyc/models/drivers-license.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/models/evidence.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/models/passport.yaml
Adds details to partner statement guide that:
- highlights using passall, random names and strings for more reliable test case generation.
- adds warning block to warn about incorrect region being passed to partner statements endpoint
- refines descriptions to be more Australia friendly
updates evidenceType inside OAS spec for partner statements to clarify required fields for each type.
Ticket Link: https://www.notion.so/immersve/Adjust-the-public-docs-2e613b1cb06a411485b836757e17ae2e?pvs=4
> partner conducted updates

- imsv-docs-astro/astro.config.mjs
- imsv-docs-docusaurus/openapi/immersve.yaml
These endpoints are not functional, and the presence of them in the docs is misleading. May be, one day we make them work but until then they should not be publicly visible (if not removed entirely)
Ticket Link: none
> Hide webhook docs

- imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
Updated the submit kyc statement code snippet to force the user to provide the following:
- givenName
- familyName
- dateOfBirth
- yearOfBirth  
That way we would avoid getting KYC failed due to duplicate profiles which prevents the user from creating a card. 
Ticket Link: https://immersve.slack.com/archives/C06G54VDLM8/p1716779793181569
> updated submit kyc statement code snippet

- imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
- imsv-docs-docusaurus/openapi/endpoints/prerequisites/spending-prerequisites.yaml
- Rename KYC_CARD_PROGRAM_REGION_MISMATCH to KYC_PROFILE_REGION_MISMATCH  error response for spending prerequisites and update the description.
- Slight facelifting for the spending prerequisites guide
Ticket Link: https://www.notion.so/immersve/Cleanup-Rename-CARD_PROGRAM_REGION_MISMATCH-error-to-PROFILE_ALREADY_PASSED_IN_ANOTHER_REGION-d07193e037a2489182563395b504148c
Related amethyst PR: https://github.com/immersve/amethyst/pull/1698
> Rename KYC_CARD_PROGRAM_REGION_MISMATCH to KYC_PROFILE_REGION_MISMATCH

- imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
After looking into it, yearOfBirth, country, and locality are not attributes we have on the schema for a date of birth claim.
Ticket Link: https://immersve.slack.com/archives/C06G54VDLM8/p1716845464466959
> Remove erroneous properties from dob claim for partner submitted statements

- imsv-docs-docusaurus/openapi/endpoints/login/models/siwe-login-request.yaml
Add `eth-sepolia` to Siwe supported network on login-init and signup page
Test deploy url: https://320-merge--jovial-scone-ec740d.netlify.app/api-reference/sign-up/
> fix(auth): Siwe supported network

- imsv-docs-docusaurus/openapi/endpoints/funding-channel/funding-channel-create.yaml
STORAGE_ADDRESS_INVALID doesn't exist anymore.
> Remove nonexistent error code for funding channel creation

- imsv-docs-astro/markdoc.config.mjs
- imsv-docs-astro/src/components/Figure.astro
- imsv-docs-astro/src/content/docs/guides/card-issuing-apps/issue-a-virtual-card.mdoc
Diagrams frequently appear with just a section heading as context. The caption can now be used instead so that diagrams can be contextualized clearly within a section.
> Add image captions

- imsv-docs-astro/src/content/docs/guides/supported-chains/ethereum.mdoc
- imsv-docs-astro/src/content/docs/guides/supported-chains/polygon.mdoc
- imsv-docs-astro/src/models/ContentRegistry.mjs
- imsv-docs-astro/src/models/__tests__/models.test.mjs
Separating mainnet and testnet is not useful when there are only two networks.
> Combine mainnet/testnet tables for specific chains

- imsv-docs-astro/src/content/config.ts
- imsv-docs-astro/src/content/funding-types/ethereum-sepolia-usdc-universal-evm-test.md
- imsv-docs-astro/src/content/funding-types/polygon-amoy-usdc-universal-evm-test.md
- imsv-docs-astro/src/content/funding-types/polygon-usdc-universal-evm-live.md
- imsv-docs-astro/src/models/FundingType.mjs
- imsv-docs-astro/src/models/__tests__/models.test.mjs
Allow arbitrary funding type names
Token is no longer derived from funding type name. Funding type name
does not need to contain network or protocol name.
Depends on: #325
> Arbitrary funding type names

- imsv-docs-docusaurus/openapi/endpoints/funding-channel/funding-channel-create.yaml
- imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel.yaml
- imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/create-withdrawal-intent.yaml
- imsv-docs-docusaurus/openapi/endpoints/prerequisites/models/get-spending-prerequisite-response.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/execute-simulator-deposit.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/execute-simulator-withdrawal.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/execute-deposit-request.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/execute-withdrawal-request.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/simulator-deposit-funding-source-interaction.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/simulator-withdrawal-funding-source-interaction.yaml
- imsv-docs-docusaurus/openapi/immersve.yaml
- imsv-docs-docusaurus/openapi/models/simulator-deposit.yaml
- Added Simulator Execute Deposit API [Docs](https://335-merge--jovial-scone-ec740d.netlify.app/api-reference/execute-simulator-deposit/)
- Added Simulator Execute Withdrawal API [Docs](https://335-merge--jovial-scone-ec740d.netlify.app/api-reference/execute-simulator-withdrawal/)
- Added `simulator_call` instruction to spending pre-requisites [endpoint](https://335-merge--jovial-scone-ec740d.netlify.app/api-reference/get-spending-prerequisites/)
- Added withdrawal execution instruction for funding source using simulator strategy. Endpoint [here](https://335-merge--jovial-scone-ec740d.netlify.app/api-reference/create-withdrawal-intent/)
Preview [here](https://335-merge--jovial-scone-ec740d.netlify.app)
Ticket Link: https://www.notion.so/immersve/public-documentation-ec1b7d9efe8d4392918b7f1 …
> Simulator Execution deposits and withdrawals

- imsv-docs-astro/src/content/config.ts
- imsv-docs-astro/src/content/docs/guides/funding-protocols/flexi-algorand-funding-protocol.mdoc
- imsv-docs-astro/src/content/networks/algorand-mainnet.md
- imsv-docs-astro/src/content/networks/algorand-testnet.md
- imsv-docs-astro/src/models/DeployedFundingProtocol.mjs
- imsv-docs-astro/src/models/SupportedNetwork.mjs
- imsv-docs-astro/src/models/__tests__/models.test.mjs
App id is more useful because the Algorand contract address is derived from the app id.
> Add algorand app ids

- imsv-docs-astro/src/content/docs/resources/public-sandbox-account.mdoc
Adding the id of the simulator funding channel created for the public Sandbox account
Ticket Link: https://www.notion.so/immersve/add-PROD-test-mode-simulator-funding-channels-3747138f015f4d5ab0c9c42136fb8313?pvs=4
> Adding sandbox simulator funding channel id

- imsv-docs-astro/markdoc.config.mjs
- imsv-docs-astro/src/components/EndpointRef.astro
- imsv-docs-astro/src/components/icons/Bookmark.astro
- imsv-docs-astro/src/content/docs/guides/card-issuing-apps/custodial-on-chain-card-issuing-integration.mdoc
Improve the structure and style of the custodial integrator guide. The substance of the guide has not been impacted. The changes are:
* Re-organize sections and update headings
* Condense section introductions into a single paragraph.
* Add {% endpointref %} callout component for every example API call.
* Use {% link %} component for guide links.
* Minor wording adjustments.
* Fix whitespace for example bash scripts.
> Integrator guide tidyup

- imsv-docs-astro/src/content/docs/guides/funding-protocols/funding-protocols.mdoc
We don't support this functionality. Partners are asking for it because they see it here.
> remove reference to unsupported webhook funding

- starlight/components/imsv/TableOfContents.astro
Increase contrast between header style and initial highlighted "overview" item.
Before:
After:
> Tweak ToC header style

- starlight/components/imsv/Header.astro
Add header links to match figma design
Ticket Link: [Notion task](https://www.notion.so/immersve/Style-Improvement-header-nav-links-cb84fbff6add49778654aa27b24d9b0a?pvs=4)
Left aligned to content in full width:
Centered on tablet width:
Hidden on mobile:
> Add header links to match figma design

- imsv-docs-docusaurus/openapi/endpoints/kyc/models/ADDRESS.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/models/DOB.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/models/FULL_NAME.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/models/StructuredAddress.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/models/UnstructuredAddress.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/models/claims.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/models/retrieve-kyc-statement-response.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/submit-partner-kyc-statement.yaml
Updates the documentation around address claims.
Fixes up the example for `GET Partner statements` to show a valid example.
Ticket Link: https://www.notion.so/immersve/Update-references-and-guides-be1cff22e93945dcb0c6bbb31b645039?pvs=4
> add partner statement address updates

- imsv-docs-astro/public/postman/collection.json
- imsv-docs-astro/src/content/docs/guides/authentication.mdoc
Going through the docs, any fixes i find...
* Removes auth inheritance from submit partner statement (since this is done by api key only)
* Updates to Partner Statements request
* Makes passport a random string 
* Creates a random date of birth
* Creates a random street number
* Sets the Spending prerequisites to request AU for region to match up with region in Partner statement
* Adds update-kyc-profile scope to login to allow access to GET kyc profile 
Ticket Link: https://immersve.slack.com/archives/C04UUJR3G2X/p1721288116868469
> Fixes as i find them

- imsv-docs-docusaurus/openapi/endpoints/kyc/models/StructuredAddress.yaml
Code examples used to show `"country": "string"` in submit KYC partner statement endpoint, now they should NZ.
> Changing example country to NZ

- imsv-docs-astro/src/styles/tailwind.css
A hidden ::before element was added on each header in commit:22b803ca5ec64a436c710ae36b428d87c86069ad. This extra element compensates for the fixed site heading, which was hiding content, but it overlaps with the previous paragraph. Since the later dom element has a higher natural z-index the text selection behavior acts strangely; the heading would be selected when selecting text between lines from the previous paragraph.
> Prevent out-of-order heading selection

- imsv-docs-docusaurus/openapi/endpoints/accounts-custodial/account-cancel-custodial.yaml
- imsv-docs-docusaurus/openapi/endpoints/accounts-custodial/account-create-custodial.yaml
- imsv-docs-docusaurus/openapi/endpoints/accounts-custodial/account-single-custodial.yaml
- imsv-docs-docusaurus/openapi/endpoints/cards/card-activate-custodial.yaml
- imsv-docs-docusaurus/openapi/endpoints/cards/card-block-custodial.yaml
- imsv-docs-docusaurus/openapi/endpoints/cards/card-close-custodial.yaml
- imsv-docs-docusaurus/openapi/endpoints/cards/card-create-custodial.yaml
- imsv-docs-docusaurus/openapi/endpoints/cards/card-get-custodial.yaml
- imsv-docs-docusaurus/openapi/endpoints/cards/card-get-secure-custodial.yaml
- imsv-docs-docusaurus/openapi/endpoints/cards/card-set-pin.yaml
- imsv-docs-docusaurus/openapi/endpoints/cards/card-unblock-custodial.yaml
- imsv-docs-docusaurus/openapi/endpoints/client-application/client-application-get.yaml
- imsv-docs-docusaurus/openapi/endpoints/client-application/client-application-update-origins.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/get-kyc-profile.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/retrieve-partner-kyc-statement.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/submit-partner-kyc-statement.yaml
- imsv-docs-docusaurus/openapi/endpoints/login/logout.yaml
- imsv-docs-docusaurus/openapi/immersve.yaml
- imsv-docs-docusaurus/openapi/models/api-key-auth.yaml
Auth scheme naming is improved. Both access token and api key auth schemes have "Target Account" variant. All endpoints except for login, logout and token exchange now use the default auth scheme.
> Fixup openapi auth schemes

- imsv-docs-astro/public/postman/collection.json
- imsv-docs-docusaurus/openapi/endpoints/kyc/get-kyc-profile.yaml
Reflect the recent changes to the use of the GET KYC profile endpoint:
- update-kyc-profile scope is discontinued, cardholder-partner achieves what's required
- you can now get KYC profile by either identity or cardholder account
- getting KYC details requires to be requested explicitly by passing `withPersonalDetails`
Ticket Link: https://www.notion.so/immersve/Get-KYC-profile-endpoint-1abe90f3952344feac7276f27a29305f?pvs=4
> Update docs for GET KYC profile endpoint

- starlight/components/imsv/TableOfContents.astro
The <script> tag needs appear at the top level in the Astro component.
> Fix TOC current selection highlighting

- imsv-docs-astro/markdoc.config.mjs
- imsv-docs-astro/src/content/docs/resources/public-sandbox-account.mdoc
- imsv-docs-astro/src/styles/tailwind.css
Using display:block for tables makes them ugly when the content is not long such as with the environments table on the integrator guide. Restore default display:table for table elements and instead surround tables with an overflow-x-auto div.
The sandbox account table content is explicitly wrapped with <wbr> tags.
> Fix display of tables with unwrapable content

- imsv-docs-astro/markdoc.config.mjs
Wrapping tables with an addition overflow div broke the prose table styles because the table is no longer a direct child of the prose element.
The authentication guide has several tables which clearly show the additional whitespace which is removed with this change.
> Fix table margins

- imsv-docs-astro/src/content/docs/guides/card-issuing-apps/custodial-on-chain-card-issuing-integration.mdoc
- imsv-docs-astro/src/content/docs/guides/card-issuing-apps/web3-wallet-card-issuing-integration.mdoc
- imsv-docs-astro/src/content/docs/guides/regions.mdoc
- imsv-docs-docusaurus/openapi/endpoints/supported-regions/get-supported-regions.yaml
Updates the region guide. Adds script commands to guide. Fixes up auth in swagger to show api key only.
Adds region to the Custodial Guide, and amends the Web3 integrators guide.
> Update supported regions guide

- imsv-docs-docusaurus/openapi/endpoints/cards/models/card.yaml
Fields are legacy. 
https://github.com/immersve/amethyst/pull/2267
https://github.com/immersve/amethyst/pull/2270
Ticket Link: https://www.notion.so/immersve/Add-E6-attributes-and-region-to-card-model-0f50a4c7e7a2470da15caa34755c54f8
> Chore: remove legacy fields on card model

- imsv-docs-astro/src/content/docs/guides/card-issuing-apps/custodial-card-issuing-integration.mdoc
- imsv-docs-astro/src/content/docs/guides/card-issuing-apps/custodial-on-chain-card-issuing-integration.mdoc
- imsv-docs-astro/src/content/docs/guides/card-issuing-apps/web3-wallet-card-issuing-integration.mdoc
- imsv-docs-astro/src/content/docs/index.mdoc
- imsv-docs-astro/src/content/docs/use-cases/_custodial-next-steps.mdoc
The on-chain custodial guide is still present in the docs but is now hidden in the side nav. The new custodial guide is shown instead.
> Promote new custodial guide

- imsv-docs-docusaurus/openapi/endpoints/funding-sources/create-funding-source.yaml
- imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/create-funding-source-for-custodial-cardholder.yaml
- imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/create-funding-source-for-login-wallet.yaml
- imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/create-funding-source-for-simulator.yaml
- imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/create-funding-source-for-wallet-signature.yaml
There were a lot of references to EVM and funding source is a much more generic operation nowadays.
- Adding more examples to cover custodial and simulator funding sources
- Removed ERC-1271 references as is no longer supported
- Added links to funding protocol guides
- accountId can also be a partner account now, so removed references to cardholder account and just left generic account
Ticket Link:  https://www.notion.so/immersve/Document-how-to-create-a-funding-source-1021d446ed8a8029868aeea92cafcd8f?pvs=4
> Funding source endpoint wording improvements

- imsv-docs-astro/src/content/docs/guides/funding-protocols/custodial-funding-protocol.mdoc
Remove network message attributes from custodial notification
Ticket Link: https://www.notion.so/immersve/remove-network-message-fields-1061d446ed8a80cb8cb2f2e3e4949bb5
> Remove network message attributes from custodial notification

- imsv-docs-astro/public/postman/collection.json
- imsv-docs-astro/src/content/docs/guides/card-issuing-apps/custodial-card-issuing-integration.mdoc
- imsv-docs-astro/src/content/docs/guides/card-issuing-apps/custodial-on-chain-card-issuing-integration.mdoc
- imsv-docs-astro/src/content/docs/guides/card-issuing-apps/web3-wallet-card-issuing-integration.mdoc
- imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc
- imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
- imsv-docs-docusaurus/openapi/endpoints/prerequisites/models/get-spending-prerequisite-request.yaml
`kycRegion` has been made optional when calling spending prerequisites
- Removed `kycRegion` from curl requests
Validation is now done against the card program regions
- Updated wording on KYC guides
Ticket Link: https://www.notion.so/immersve/Update-public-docs-1121d446ed8a8019963ed67a88d33c9e?pvs=4
> Remove kycRegion from guides

- imsv-docs-docusaurus/openapi/endpoints/simulator/models/authorize-request.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/reverse-request.yaml
Simulator authorize supports two types `refund` and `purchase`.
Reversal does not. It will have the type of the original auth.
> add refund type to simulator

- imsv-docs-astro/src/content/docs/guides/funding-protocols/custodial-funding-protocol.mdoc
Reversal declined events do not trigger custodial notifications.
> Remove the reversal declined events from custodial payload

- imsv-docs-docusaurus/openapi/endpoints/simulator/models/clear-request-base.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/clear-request.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/reverse-request.yaml
Simulator APIs should all accept transactionAmount and currencyCode. APIs will handle conversion to billing amount in the simplest way.
Reversal API transactionAmount will have the meaning of reversing the auth or clearing TO the transactionAmount.
Ticket Link: https://www.notion.so/immersve/Update-docs-1341d446ed8a80c7a2b9c150a5424e49?pvs=4
https://immersve.slack.com/archives/C07HU5LGYSU/p1730434155995389?thread_ts=1730409667.677409&cid=C07HU5LGYSU
PRs:
https://github.com/immersve/amethyst/pull/2611
https://github.com/immersve/amethyst/pull/2601
https://github.com/immersve/amethyst/pull/2600
> Simulator - All endpoints use transactionAmount in any currency

- imsv-docs-docusaurus/openapi/endpoints/prerequisites/spending-prerequisites.yaml
Removes the action type and type from the example 
Ticket Link: https://www.notion.so/immersve/Fix-the-docs-1371d446ed8a8044a8e4ddf7db095596?pvs=4
> fix example for aml prereq

- imsv-docs-docusaurus/openapi/endpoints/simulator/models/execute-deposit-request.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/execute-withdrawal-request.yaml
Description says correct thing
```
amount: string
Withdrawal amount in minor units.
```
but example before this change displays number instead of numeric string
```
{
"amount": 300000000,
"fundingSourceId": "91ad6fea3b52ca58d60d7fd310f789ec"
}
```
> Simulator amount param is a string

- imsv-docs-docusaurus/openapi/endpoints/simulator/authorize.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/authorize-request.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/clear-request-base.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/merchant.yaml
- Adds new merchant field to authorize and clear simulator endpoints
- Documents existing but undocumented `forcePost` field
Ticket Link: https://www.notion.so/immersve/Add-ability-to-set-Card-acceptor-country-in-Simulator-API-1481d446ed8a8075a0fbeafe921c4f09?pvs=4
> Add merchant to auth and clearing & document forcePost

- imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/create-funding-source-for-custodial-cardholder.yaml
- imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/funding-source.yaml
Added externalId as required for custodial cardholder context, and removed "cardholder" as singular context for accountId within Get Funding Source.
> 1st tidy up of funding source for custodial context

- imsv-docs-docusaurus/openapi/endpoints/funding-sources/list-funding-sources.yaml
- imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/funding-source.yaml
Get funding sources now supports partner account ID as a param as well as cardholder account ID. Doc is updated to use general 'Account' language rather than specifically 'cardholder'.
Ticket Link: https://www.notion.so/immersve/Update-public-documentation-14b1d446ed8a8082a6b7deab485aa711?pvs=4
> Update get funding sources doc

- imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
Immersve was spelled wrong.
Ticket Link: https://immersve.slack.com/archives/C06G54VDLM8/p1732905879573839
> typo in partner conducted guide

- imsv-docs-docusaurus/openapi/endpoints/simulator/models/execute-deposit-request.yaml
The `amount` field of the body has an incorrect description that references withdrawal instead of deposit.
> fix: Execute simulator deposit description

- imsv-docs-astro/src/content/docs/guides/testing/passing-kyc-in-test.mdoc
Use 'unique' instead of 'random' to describe which attributes in KYC application need to be uniquely generated to avoid duplicate failure.
Ticket Link: Feedback from [Product showcase](https://www.notion.so/immersve/Product-Showcase-2024-12-13-1591d446ed8a809dbfc2c614c2aae096?pvs=4)
> Use 'unique' instead of 'random' in KYC testing guide

- imsv-docs-docusaurus/openapi/endpoints/cards/models/card.yaml
Example is in the correct format, but it's not mentioned explicitly.
> Explicit card expiry fromat

- yarn.lock
fixes : https://github.com/immersve/immersve-docs/security/dependabot/83
> upgrade express to upgrade path to regex

- imsv-docs-astro/astro.config.mjs
- imsv-docs-astro/src/content/docs/guides/funding-protocols/funding-protocols.mdoc
The goal is to draw attention to the supported chains and protocol abstractions (direct spend, custodial, etc) instead of the concrete protocols so newcomers have a more natural path to discover capabilities.
1. Order supported chains before protocols in side nav.
2. Do not call out concrete protocols in side nav.
3. Do not call out concrete protocols in flexi/universal descriptions.
> Tweak funding protocols nav

- imsv-docs-astro/astro.config.mjs
Supported tokens and supported chains should go together. Now that chains are above protocols the tokens nav should also move up.
> Move supported tokens above protocols

- imsv-docs-docusaurus/openapi/immersve.yaml
* change "Client application" to "Client Applications"
* remove duplicate "Funding Sources" label
> Fix open api section titles

- imsv-docs-astro/src/content/docs/guides/core-concepts/monetary-units.mdoc
- imsv-docs-astro/src/content/docs/guides/funding-protocols/custodial-funding-protocol.mdoc
- imsv-docs-astro/src/content/docs/guides/funding-protocols/funding-types.mdoc
- imsv-docs-astro/src/content/docs/guides/supported-tokens/supported-tokens.mdoc
- imsv-docs-astro/src/content/docs/use-cases/_custodial-how-it-works.mdoc
- imsv-docs-astro/src/content/docs/use-cases/blockchains.mdoc
Stablecoin is more commonly written as a single word.
> Change "stablecoin" to one word

- imsv-docs-docusaurus/openapi/endpoints/cards/card-get.yaml
Adds new documented property.
Prefixing boolean with 'is' would be consistent with naming other boolean properties in our API (isBlocked in Get Card details, isAvailable in Get Supported Regions, isActive in Get Account, etc). However isBlocked is getting deprecated soon, and not prefixing with is adds conciseness.
Ticket Link: 
- https://immersve.slack.com/archives/C084R4DTLRL/p1740439397848179?thread_ts=1740341493.982319&cid=C084R4DTLRL
- https://www.notion.so/immersve/Docs-1a61d446ed8a8082a9d3cf6ad3260ed3?pvs=4
Related PR:
- https://github.com/immersve/amethyst/pull/3324/files#diff-bbab05d3a3569067f8a43047281b01b5651b7d6138c9390eb26cf9a1d1601cd8
> Add new property unfreezeAllowed

- imsv-docs-astro/src/content/docs/guides/funding-protocols/universal-evm-funding-protocol.mdoc
The name attribute does not need to be *globally* unique. Rather it only needs to be unique for the address of the message sender.
> Improve Universal EVM Funds Storage "name" description

- imsv-docs-astro/src/components/registry-views/tokens/NetworkTokensTable.astro
- imsv-docs-astro/src/components/registry-views/wrappableAddress.mjs
On smallest screen sizes the test tokens table overflows and the "faucet" column is completely hidden. Making addresses wrap at 24 chars brings the faucet column partially into view. Preventing wrapping of the faucet column improves the row height.
> Improve column widths on test tokens table

- imsv-docs-docusaurus/openapi/endpoints/prerequisites/models/get-spending-prerequisite-response.yaml
- imsv-docs-docusaurus/openapi/endpoints/prerequisites/spending-prerequisites.yaml
- imsv-docs-docusaurus/openapi/models/contact-channel-email-params.yaml
- imsv-docs-docusaurus/openapi/models/contact-channel-phone-params.yaml
- imsv-docs-docusaurus/openapi/models/kyc-params.yaml
- Simplify Get Spending Prerequisites endpoint summary.
- Add missing prerequisite instruction params descriptions and rename the prerequisite param types: "Blockchain Funding Params", "Simulator Funding Params" and "KYC Params".
- Deprecate KYC prerequisite `params.status`. The `params.reasons` array and the prerequisite status can be used instead.
- The deprecated KYC `params.status` and prerequisite `type` are defocused by moving to end of attribute lists, and have a condensed clear description with client instructions for correct alternative.
- Remove prerequisite params for phone/email which do not have any meaningful parameters.
- Improve KYC `params.reasons` and `kycUrl` descriptions. Reasons is no longer coupled with KYC check failures and may be used for Immersve-conducted KYC. …
> Tidy up Get Spending Prerequisites response specification

- .github/pull_request_template.md
Postman collection is being missed when APIs are being updated. This just adds a callout. Not a checkbox. Those didn't prove that effective. Will bring this up in tech catchup and champion this.
Ticket Link: https://www.notion.so/immersve/Update-docs-PR-template-1d21d446ed8a80d2b158dcba6abf5535?source=copy_link
> Postman update reminder in PR description template.

- imsv-docs-docusaurus/package.json
- yarn.lock
Going from 3.0 to 4.5 there there are many improvements and fixes. Version 4 requires Docusaurus upgrade to version 3.5+.
Command to upgrade was:
yarn up @docusaurus/core @docusaurus/preset-classic docusaurus-plugin-openapi-docs docusaurus-theme-openapi-docs
> Update docusaurus openapi plugin

- imsv-docs-docusaurus/openapi/endpoints/kyc/models/DRIVERS_LICENSE.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/models/NATIONAL_ID.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/models/PASSPORT.yaml
- imsv-docs-docusaurus/openapi/endpoints/kyc/models/evidence.yaml
add national id for evidence in "Submit KYC Statement" for BR, AR and MX
also fix a bug for driver license and passport that they can not show the properties 
Ticket Link: [_link_here_](https://www.notion.so/immersve/update-doc-for-partner-kyc-submition-2131d446ed8a8072b0fae03d5bfd87ce?source=copy_link)
test deploy: https://686-merge--jovial-scone-ec740d.netlify.app/api-reference/submit-kyc-statement/
> feature(kyc): add national id for evidence in Submit KYC Statement

- imsv-docs-docusaurus/openapi/endpoints/funding-sources/models/fsi/payment-fsi-context.yaml
- imsv-docs-docusaurus/openapi/endpoints/transactions/models/transaction.yaml
Update the transaction and fsi examples to use an immersve id.
Ticket Link: https://www.notion.so/immersve/Update-docs-2311d446ed8a80bc902de5de3bc9a568?source=copy_link
> Update the transaction and fsi examples to use an immersve id

- imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel-params/algorand.yaml
- imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel-params/custodial.yaml
- imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel-params/simulator.yaml
- imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/create-funding-channel-params/universal-evm.yaml
Perhaps this used to work in a previous version but now without the "type: object" declaration the properties are not rendered.
> Fix funding channel params openapi spec

- imsv-docs-docusaurus/openapi/endpoints/simulator/models/reverse-request-base.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/reverse-request.yaml
Simulator reversal has a bug as it doesn’t show authorizationRequestMsg and clearingRequestMsg as required fields in the payload.
Found the bug while looking into https://www.notion.so/immersve/Update-simulator-to-add-field-95-on-a-full-reversal-2501d446ed8a80b8a895f2e788de1a1f?source=copy_link
Test deploy link: https://696-merge--jovial-scone-ec740d.netlify.app/
> Fix: Simulator reversal issue not showing required request payload.

- imsv-docs-docusaurus/openapi/endpoints/cards/models/card.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/authorize-request.yaml
- imsv-docs-docusaurus/openapi/endpoints/simulator/models/clear-request-base.yaml
Document limit of $1000 in card issuance currency on Simulator requests.
Amethyst change: https://github.com/immersve/amethyst/pull/4438
Ticket Link: https://www.notion.so/immersve/Implement-amount-limit-on-simulator-requests-2521d446ed8a80488f29c81a44cb6dd6
> Simulator Request Amount Limit

- imsv-docs-docusaurus/openapi/immersve.yaml
Use condensed format for endpoint refs and hostnames. Use whitespace and comments for delineating endpoint groupings.
> Tidy up openapi path organization
